### ISSUE TITLE
Add News Bias Analyzer

### ISSUE THREAD

**Issue by davidpcahill** [devisasari/awesome-chatgpt-store#13]
Please add my custom GPT. Demo video and link information are below:

GPT Link: https://chat.openai.com/g/g-9tbHB4O4r-news-bias-analyzer

Demo: https://x.com/CybrixAI/status/1725075545816485981?s=20

**Comment by TagWolf** [comment]
Here's the description and logo if you need:

# Description
Targeted Bias Detection with Graphing, Summarization, Categorization, Tagging, and Comprehensive Source Evaluation

# Logo
![image](https://github.com/devisasari/awesome-chatgpt-store/assets/8665128/70b7267b-b477-4050-8053-88206e354d48)

**Comment by devisasari** [comment]
Hello, you can open a PR.
