### ISSUE TITLE
Add CustomGPT-Pump University

### ISSUE THREAD

**Issue by acramire** [devisasari/awesome-chatgpt-store#9]
Add Pump University GPT link under the Health & Fitness Section: 
- [Pump University](https://chat.openai.com/g/g-cgJkNatgi-pump-university) - The Ultimate AI fitness coach, crafting personalized workouts with adaptable exercise options and visual YouTube videos, suited for any fitness level and goal

Thank you :) !

**Comment by devisasari** [comment]
Great 🚀
